version: '3.1'
services:
  cursos:
    build: ../
    container_name: cursos
    image: cursos
    environment:
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgresdb
      - POSTGRES_DATABASE=postgres
    ports:
      - "3001:3000"
  authentication:
    build: ../
    container_name: authentication
    image: authentication
    environment:
      - MICROSSERVICE_TYPE=auth
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgresdb
      - POSTGRES_DATABASE=postgres
    ports:
      - "3000:3000"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql